
networks:
  nw:
    driver: bridge

services:
  books:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgredb:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=1029384756
    ports:
      - "8080:8080"
    depends_on:
      - postgredb
    networks:
      - nw
  postgredb:
    image: 'bitnami/postgresql:17'
    environment:
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=1029384756
    networks:
      - nw
    ports:
      - "5434:5432"
